myatoi : myatoi.o my-tests.o
	gcc -o myatoi myatoi.o my-tests.o

mytests.o : my-tests.c
	gcc -o my-tests.o -c my-tests.c -pedantic -Wall -Werror

myatoi.o : myatoi.c
	gcc -o myatoi.o -pedantic -Wall -c myatoi.c
